---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: infrastructure
  description: Area de infrastructure
  links:
    - url: https://synera.com.br
      title: Developer portal
      icon: help
spec:
  type: organization
  owner: group:cloud
  subdomainOf: domain:technology
