---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: synera2
  description: Everything related to Synera tenant
  links:
    - url: http://example.com/domain/audio/
      title: Domain Readme
    - url: http://example.com/domains/audio/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  type: tenant
  owner: guest
  children: [technology]