---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: handler-kubernetes
  description: Serviço que faz interação com alguns objetos do kubernetes
  tags:
    - golang
    - cloud
    - k8s
    - platform
spec:
  type: openapi
  lifecycle: production
  owner: group:golang
  system: platform
  definition:
    $text: ./openapi.yaml