---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: developer-terraform
spec:
  profile:
    displayName: Developer 003
    email: contato@synera.com.br
  memberOf: [infras-as-a-code]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: developer-argocd
spec:
  profile:
    displayName: Developer 004
    email: contato@synera.com.br
  memberOf: [infras-as-a-code]