apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  description: A collection of all groups from tenant
  name: groups
spec:
  targets:
    - ./cloud.yaml
    - ./iaac.yaml
    - ./platform.yaml
    - ./golang.yaml