---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
  description: Equipe de que gerencia a developer platform
  links:
    - url: https://synera.com.br
      title: Developer portal
      icon: help
  tags:
    - centralizado
spec:
  type: squad
  profile:
    displayName: platform
    email: contato@synera.com.br
  children: []
