apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
  description: Equipe de que gerencia a developer platform
  tags:
  - centralizado
spec:
  type: squad
  profile:
    displayName: platform
    email: platform@.infra.synera.com.br
  children: []
