---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    sonarqube.org/project-key: 'synera-br_platform-demo'
    github.com/project-slug: 'synera-br/platform-demo'
  name: aws-sync
  description: Valida status dos recursos da aws
  tags:
    - platform
    - aws
    - sync
spec:
  type: service
  lifecycle: production
  owner: group:cloud
  system: platform
  consumesApis: ['handler-kubernetes']
  dependsOn:
    - 'resource:sqs'
    - 'resource:postgresql'
