---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    sonarqube.org/project-key: 'Tomelin_fc-desafio-db'
    github.com/project-slug: 'synera-br/platform-demo'
  name: azure-sync
  description: Valida status dos recursos da azure
  links:
    - url: https://synera.com.br
      title: Developer portal
      icon: help
  tags:
    - platform
    - aws
    - sync
spec:
  type: service
  lifecycle: production
  owner: group:cloud
  system: platform
  consumesApis: ['handler-kubernetes']
  dependsOn:
    - 'resource:sqs'
    - 'resource:postgresql'
