---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    sonarqube.org/project-key: 'synera-br_platform-demo'
    github.com/project-slug: 'synera-br/platform-demo'
  name: backend-platform
  description: Serviço backend do developer platform
  tags:
    - backend
    - platform
spec:
  type: service
  lifecycle: production
  owner: group:golang
  system: platform
  consumesApis: ['handler-kubernetes']
  dependsOn:
    - 'resource:sqs'
    - 'resource:mongo'
    - 'resource:redis'
