---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    sonarqube.org/project-key: 'synera-br_platform-demo'
    github.com/project-slug: 'synera-br/platform-demo'
  name: deploy-resources-cp
  description: Deploy de recursos cloud através do crossplane
  links:
    - url: https://synera.com.br
      title: Developer portal
      icon: help
  tags:
    - iaac
    - cloud
    - platform
spec:
  type: crossplane
  lifecycle: production
  owner: group:infras-as-a-code
  system: platform
  providesApis:
    - cloud
  consumesApis: ['component:process']
  dependsOn:
    - 'resource:eks'
