---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: handler-kubernetes
  description: Serviço que faz interação com alguns objetos do kubernetes
  links:
    - url: https://synera.com.br
      title: Developer portal
      icon: help
  tags:
    - golang
    - cloud
    - k8s
    - platform
spec:
  type: service
  lifecycle: production
  owner: group:golang
  system: platform
  providesApis:
    - handler-kubernetes
  dependsOn:
    - 'resource:sqs'
    - 'resource:redis'
    - 'resource:mongo'
