---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    sonarqube.org/project-key: 'synera-br_platform-demo'
  name: handler-kubernetes
  description: Serviço que faz interação com alguns objetos do kubernetes
  tags:
    - golang
    - cloud
    - k8s
    - platform
spec:
  type: service
  lifecycle: production
  owner: group:golang
  system: platform
  providesApis:
    - handler-kubernetes
  dependsOn:
    - 'resource:sqs'
    - 'resource:redis'
    - 'resource:mongo'
