---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    sonarqube.org/project-key: 'synera-br_platform-demo'
    github.com/project-slug: 'synera-br/platform-demo'
  name: deploy-resources-tf
  description: Deploy de recursos cloud através do terraform
  tags:
    - iaac
    - cloud
    - platform
spec:
  type: terraform
  lifecycle: production
  owner: group:infras-as-a-code
  system: platform
  providesApis:
    - cloud
  consumesApis: ['component:process']
  dependsOn:
    - 'resource:redis'
