---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    sonarqube.org/project-key: 'synera-br_platform-demo'
    github.com/project-slug: 'synera-br/platform-demo'
  name: frontend-platform
  description: Serviço frontend do developer platform
  links:
    - url: https://synera.com.br
      title: Developer portal
      icon: help
  tags:
    - frontend
    - platform
spec:
  type: website
  lifecycle: production
  owner: group:platform
  system: platform
  providesApis:
    - cloud
  consumesApis: ['component:process']
  dependsOn:
    - 'resource:redis'
    - 'resource:ingress'
