---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    backstage.io/view-url: https://github.com/Tomelin/desafio-stn/tree/develop/catalog/catalog.info.yaml
    backstage.io/edit-url: https://github.com/Tomelin/desafio-stn/edit/develop/catalog/catalog.info.yaml
    backstage.io/source-location: url:https://github.com/Tomelin/desafio-stn/tree/develop/catalog/
    snyk.io/org-id: 8516c00c-37c2-445e-858e-3a7feb69d38e
    snyk.io/targets: Tomelin/desafio-stn
    snyk.io/project-ids: 94807e09-fd98-416c-8971-5e3fbf33aba1
    sonarqube.org/project-key: 'Tomelin_desafio-stn'
    github.com/project-slug: 'Tomelin/desafio-stn'
  name: frontend-platform
  description: Serviço frontend do developer platform
  tags:
    - frontend
    - platform
spec:
  type: website
  lifecycle: production
  owner: group:platform
  system: platform
  providesApis:
    - cloud
  consumesApis: ['component:process']
  dependsOn:
    - 'resource:redis'
    - 'resource:ingress'
