---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: redis
  description: Cache Redis
  labels:
    managedBy: terraform
  tags:
  - cache
  - azure
spec:
  type: cache
  owner: group:cloud
  system: platform