---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mongo
  description: MongoDB
  labels:
    managedBy: terraform
  tags:
  - nosql
  - azure
spec:
  type: database
  owner: group:cloud
  system: platform