---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql
  description: PostgreSQL
  annotations:
    synera.io/managedBy: crossplane
  tags:
    - sql
    - aws
spec:
  type: database
  owner: group:cloud
  system: platform